### PR TITLE
added documentation

### PR DESCRIPTION
**Pull request by ethyreal**
since appledoc generates a docset for Xcode and Dash it makes since to keep a copy in the main repo.

### CODE REVIEW

**Comment by jalakoo** [comment]
TEALCollectConfiguration.h 
-------------------------------------

Line : 21-22: Recommend minor text change: 

After every event, after each sendEventWithData: or sendViewWithData: call an updated visitor profile will be requested. —>
**After each event (sendEventWithData: or sendViewWithData: call) an updated visitor profile will be requested**

Line: 28: Recommend minor text change:

Unsigned integer value that controls the level of logging will use during its lifecycle. ->
**Unsigned integer value that controls the verbosity level of any log output.**


TEALVisitorProfileCurrentVisit.h
--------------------------------------------

Line: 12: Typo + Recommend minor text change: 

Container object for attrubtes related a users current visit.  Similar to the TEALVisitorProfile but contains only attributes related to the users current visit. ->
**Container object for attributes related ONLY to a user’s current visit.**


Line: 52: Question regarding: 
-(NSInteger) totalEventCount;  If total counts will never be negative why not go with NSUInteger instead?

**Comment by ethyreal** [comment]
FYI inline comments work better for me as they highlight the exact code in context and there is then no need to write the file name and line number.

**Comment by ethyreal** [comment]
another advantage of inline comments is as the code is update these comments go away as the code the referred to has changed.

The comments were updated, and type changed.  I went with event type as a signed integer to avoid dealing with encoding issues of 32 bit systems, in order to make this work I am encoding as an NSNumber, it's heavy but ensures data integrity.

**Comment by jalakoo** [comment]
Noted, I'll add comments inline in the future. One addition to Readme.md, not an edit to current changes, is to add the copyright line at the bottom for legal.  See https://github.com/Tealium/ios-library/blob/master/README.md for example.

**Comment by ethyreal** [comment]
done.

**Pull request merged**
